version: 0.2

phases:
  pre_build:
    commands:
      - cp ./settings.xml /root/.m2/settings.xml
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain $DOMAIN_ACCOUNT --domain-owner $DOMAIN_OWNER --region ap-northeast-1 --query authorizationToken --output text`
  build:
    commands:
      - mvn clean 
      - mvn install 
      - mvn deploy 
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
    - '/root/.npm/**/*'